POST http://localhost:8081/products
Content-Type: application/json

{
  "name": "Samsung",
  "price": 1000,
  "quantity": 5
}

###

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "customerId": "ddd9dd26-9515-48b9-b630-12a2d61db042",
  "productId": "d11dee8a-4fb9-45e5-9c3c-13ddd2a095d8",
  "productQuantity": 1
}

###

GET http://localhost:8080/orders/1e29c021-432e-4aa5-a3a0-634dbe3a449f/history